coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        # this allows a small drop from the previous base commit coverage
        threshold: 0.5%
    patch:
      default:
        informational: true
        target: auto
        # this allows a small drop from the previous base commit coverage
        threshold: 0.5%

# comment:
#   layout: "condensed_header, condensed_files, condensed_footer"
#   require_changes: true  # only post the comment if coverage changes

# github_checks:
	# annotations: false
