[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--color=yes --doctest-modules"
testpaths = [
    # for the doctests:
    "src/spflow",
    # for the actual tests:
    "src/tests"
]

[tool.black]
line-length = 120
color = true
target-version = [
    "py37",
    "py38",
    "py39",
    "py310",
    "py311"
]

[tool.isort]
profile = "black"
py_version = 37
