name: Development Build & Test

on:
  release:
    types: [ published ]
  pull_request:
  push:

jobs:

  lint:
    name: "flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/setup.cfg
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint with flake8
        run: flake8 src/

  format-check:
    name: "format-check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/setup.cfg
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Checking imports with isort
        run: isort --check-only --color --diff src/
      - name: Checking formatting with black
        run: black --check --diff src/

  tests:
    name: Python ${{ matrix.python-version }} + PyTorch ${{ matrix.pytorch-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't fail fast to explore which configurations fail
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        pytorch-version: ['1.10.2', '1.11.0', '1.12.1', '1.13.0']
        exclude:
          - python-version: '3.10'
            pytorch-version: '1.10.2'  # 3.10 doesn't support torch<=1.11.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}, PyTorch ${{ matrix.pytorch-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/setup.cfg
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.pytorch-version }}
          pip install .[dev]
      - name: Test with pytest
        run: |
          pytest
