name: Development Build & Test

on: [push]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
        pytorch-version: [1.10.2, 1.11.0, 1.12.1, 1.13.0]
        include:
          - {name: '3.11', python-version: '3.11', os: ubuntu-latest}
          - {name: '3.10', python-version: '3.10', os: ubuntu-latest}
          - {name: '3.9', python-version: '3.9', os: ubuntu-latest}
          - {name: '3.8', python-version: '3.8', os: ubuntu-latest}
          - {name: '3.7', python-version: '3.7', os: ubuntu-latest}
          - {name: '3.6', python-version: '3.6', os: ubuntu-20.04}  # ubuntu-latest does not have python-3.6
        exclude:
          # exclude python 3.6 for torch 1.11.0.
          - pytorch-version: 1.11.0
            python-version: 3.6
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}, PyTorch ${{ matrix.pytorch-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install torch==${{ matrix.pytorch-version }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt --ignore-installed; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
