name: Development Build & Test

on:
  release:
    types: [ published ]
  pull_request:
  push:

jobs:

  "Lint":
    name: "Lint (disabled)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/pyproject.toml
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint with flake8
        run: ruff check src
        continue-on-error: true

  "Check_Format":
    name: "Check Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/pyproject.toml
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Checking formatting with black
        run: black --check --diff src/

  "Test":
    name: "Test: Py ${{ matrix.python-version }} + Torch ${{ matrix.pytorch-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't fail fast to explore which configurations fail
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # 3.12 is not yet supported by torch
        pytorch-version: ['1.11.0', '1.12.1', '1.13.1', '2.0.1', '2.1.0']
        exclude:
          - python-version: '3.11'
            pytorch-version: '1.11.0'
          - python-version: '3.11'
            pytorch-version: '1.12.1'
          # Add other incompatible combinations here
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}, PyTorch ${{ matrix.pytorch-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/pyproject.toml
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.pytorch-version }}
          pip install .[dev]
      - name: Test with pytest
        run: |
          pytest src/tests
