name: Development Build & Test

on: [push]

jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't fail fast to explore which configurations fail
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        pytorch-version: ['1.10.2', '1.11.0', '1.12.1', '1.13.0']
        exclude:
          - python-version: '3.10'
            pytorch-version: '1.10.2'  # 3.10 doesn't support torch<=1.11.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}, PyTorch ${{ matrix.pytorch-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install torch==${{ matrix.pytorch-version }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt --ignore-installed; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
