name: Development Build & Test

on:
  release:
    types: [ published ]
  pull_request:
  push:

jobs:

  "Lint":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/pyproject.toml
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint with flake8
        run: ruff check src

  "Check_Format":
    name: "Check Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/pyproject.toml
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Checking formatting with black
        run: black --check --diff src/

  "Test":
    name: "Test: Py ${{ matrix.python-version }} + Torch ${{ matrix.pytorch-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't fail fast to explore which configurations fail
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        pytorch-version: ['1.11.0', '1.12.1', '1.13.1', '2.0.1', '2.1.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}, PyTorch ${{ matrix.pytorch-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/pyproject.toml
      - name: Install library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.pytorch-version }}
          pip install .[dev]
      - name: Test with pytest
        run: |
          pytest
